title: SpacePirates
description: Piraten im Weltraum
url: https://spacepirates.jcgames.de
paginate: 10
paginate_path: "/Aktuelles/Seite_:num/"
collections_dir: collections
collections:
  Piratencrews:
    sort_by: name
  Weltraumtiere:
    sort_by: name
  Sekten:
    sort_by: name
