# This workflow creates the data files

name: create-data

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Create the data files
        run: .scripts/update.sh

      - name: Add, commit and push
        uses: EndBug/add-and-commit@v9.0.1
        with:
          add: _data/ assets/json/
          message: Update data files
          pull: NO-PULL
          push: true
